/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMaterialSymbolsDarkMode: typeof import('~icons/material-symbols/dark-mode.jsx')['default']
  const IconMaterialSymbolsSunny: typeof import('~icons/material-symbols/sunny.jsx')['default']
  const IconMingcuteCloseLine: typeof import('~icons/mingcute/close-line.jsx')['default']
  const IconMingcuteMinimizeLine: typeof import('~icons/mingcute/minimize-line.jsx')['default']
  const IconMingcuteRestoreLine: typeof import('~icons/mingcute/restore-line.jsx')['default']
  const IconMingcuteSquareLine: typeof import('~icons/mingcute/square-line.jsx')['default']
}
